import assert from 'node:assert/strict';

export async function testCategories({evaluate, until, cdp}) {
  assert.ok(await evaluate(`plugin.commands.some(c=>c.id==='open-pdf-in-annotator' && typeof c.callback==='function' && !c.checkCallback)`), 'Open command is available without an active PDF');
  await evaluate(`plugin.commands.find(c=>c.id==='open-pdf-in-annotator').callback()`);
  assert.deepEqual(await evaluate('lastPicker.items.map(f=>f.path)'), ['Forschungspapier.pdf']);
  await evaluate('lastPicker.onChooseItem(lastPicker.items[0]);lastPicker.close()');
  assert.equal(await evaluate('openedState.state.file'),'Forschungspapier.pdf');
  await evaluate(`window.activeFile=new TFile('Forschungspapier.pdf');plugin.ribbon[0].callback();window.activeFile=null`);
  assert.equal(await evaluate('openedState.type'),'pdfaw-view');
  assert.equal(await evaluate('plugin.tabs[0].getSettingDefinitions()[1].name'),'Categories');
  const open = () => evaluate(`document.querySelector('button[aria-label="Customize"]').click()`);
  const click = text => evaluate(`[...document.querySelectorAll('.pdfaw-category-modal button')].find(b=>b.textContent===${JSON.stringify(text)}).click()`);
  const name = (id,value) => evaluate(`(() => { const input=document.querySelector('[data-category-id="${id}"] input[type="text"]');input.value=${JSON.stringify(value)};input.dispatchEvent(new Event('input')); })()`);
  await open();
  assert.equal(await evaluate('document.querySelectorAll(".pdfaw-category-row").length'),6);
  assert.equal(await evaluate('document.querySelector("#pdfaw-theme-accent").value'),'#55d8c8');
  await name('claim','Discard this'); await click('Cancel');
  assert.equal(await evaluate('categories.style("claim").label'),'Claim','Cancel leaves categories unchanged');
  await open(); await name('claim','Assertion');
  await evaluate(`(() => {const color=document.querySelector('[data-category-id="claim"] input[type="color"]');color.value='#123456';color.dispatchEvent(new Event('input'));})()`);
  await evaluate(`(() => {const color=document.querySelector('#pdfaw-theme-accent');color.value='#b54cff';color.dispatchEvent(new Event('input'));})()`);
  await evaluate(`(() => {const color=document.querySelector('#pdfaw-theme-background');color.value='#0b0f0e';color.dispatchEvent(new Event('input'));})()`);
  await click('Add category');
  const id=await evaluate('document.querySelector(".pdfaw-category-row:last-child").dataset.categoryId');
  await name(id,'Hypothesis');
  await evaluate(`(() => {const row=document.querySelector('[data-category-id="${id}"]');const color=row.querySelector('input[type="color"]');color.value='#aa3366';color.dispatchEvent(new Event('input'));const icon=row.querySelector('select');icon.value='lightbulb';icon.dispatchEvent(new Event('change'));})()`);
  await click('Save categories'); await until('!document.querySelector(".pdfaw-category-modal")');
  assert.equal(await evaluate('categories.active().length'),7);
  assert.equal(await evaluate('categories.accentColor()'),'#b54cff');
  assert.equal(await evaluate('categories.themeColors().background'),'#0b0f0e');
  assert.equal(await evaluate('getComputedStyle(view.root).getPropertyValue("--pdfaw-bg").trim()'),'#0b0f0e');
  assert.equal(await evaluate('getComputedStyle(view.root).getPropertyValue("--pdfaw-accent").trim()'),'#b54cff');
  assert.equal(await evaluate('document.querySelector(".pdfaw-selection-toolbar button[aria-label=Assertion]").dataset.icon'),'quote');
  assert.equal(await evaluate('document.querySelector(".pdfaw-selection-toolbar button[aria-label=Hypothesis]").dataset.icon'),'lightbulb');
  assert.equal(await evaluate('(async()=> (await reloadCategories()).find(x=>x.label==="Hypothesis").hex)()'),'#aa3366');
  assert.equal(await evaluate('pluginData.theme.accent'),'#b54cff');
  await evaluate(`(() => {const span=document.querySelector('.pdfaw-textlayer span');const r=document.createRange();r.selectNodeContents(span);getSelection().removeAllRanges();getSelection().addRange(r);view.captureSelection();document.querySelector('.pdfaw-selection-toolbar button[aria-label="Hypothesis"]').click();})()`);
  assert.equal(await evaluate('document.querySelector(".modal select").value'),id);
  await evaluate(`(() => {const body=document.querySelector('.pdfaw-editor-body');body.value='Custom category comment';body.dispatchEvent(new Event('input'));[...document.querySelectorAll('.modal button')].find(b=>b.textContent==='Save').click();return view.saveQueue;})()`);
  assert.equal(await evaluate('view.sidecar.annotations.at(-1).category'),id);
  assert.equal(await evaluate('view.sidecar.annotations.at(-1).categoryStyle.hex'),'#aa3366');
  await cdp('Emulation.setDeviceMetricsOverride',{width:320,height:941,deviceScaleFactor:1,mobile:false});
  await open();
  assert.ok(await evaluate(`(()=>{const r=document.querySelector('.pdfaw-category-modal').getBoundingClientRect();return r.width<=innerWidth;})()`),'Category dialog fits a narrow window');
  await click('Cancel');
  await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:941,deviceScaleFactor:1,mobile:false});
  await open();
  await evaluate(`document.querySelector('[data-category-id="${id}"] .pdfaw-category-delete').click();document.querySelector('[data-category-id="note"] .pdfaw-category-delete').click()`);
  await click('Save categories'); await until('!document.querySelector(".pdfaw-category-modal")');
  assert.equal(await evaluate('document.querySelector(".pdfaw-selection-toolbar button[aria-label=Hypothesis]")'),null);
  assert.equal(await evaluate('categories.preferred()'),'claim');
  assert.equal(await evaluate('view.sidecar.annotations.at(-1).comment'),'Custom category comment');
  await evaluate('view.editAnnotation(view.sidecar.annotations.at(-1))');
  assert.ok(await evaluate('document.querySelector(".modal select").selectedOptions[0].textContent.endsWith("(deleted)")'));
  await evaluate(`[...document.querySelectorAll('.modal button')].find(b=>b.textContent==='Save').click();view.saveQueue`);
  await evaluate(`view.onLoadFile(new TFile('Forschungspapier.pdf'))`);
  assert.equal(await evaluate('categories.forAnnotation(view.sidecar.annotations.at(-1)).label'),'Hypothesis');
  await open();await name('claim','Renamed after disk failure');
  await evaluate('window.failSettingsSave=true');await click('Save categories');
  await until('document.querySelector(".pdfaw-category-error").textContent.includes("Disk unavailable")');
  assert.equal(await evaluate('categories.style("claim").label'),'Assertion');
  await evaluate('window.failSettingsSave=false');await click('Save categories');
  await until('!document.querySelector(".pdfaw-category-modal")');
  assert.equal(await evaluate('categories.style("claim").label'),'Renamed after disk failure');
  await open();
  await evaluate(`while(document.querySelectorAll('.pdfaw-category-row').length>1) document.querySelector('.pdfaw-category-delete').click()`);
  assert.ok(await evaluate('document.querySelector(".pdfaw-category-delete").disabled'),'Cannot delete the last category');
  await click('Cancel');
  assert.equal(await evaluate('categories.active().length'),5);
  console.log('PASS: always-visible PDF command, picker, ribbon, category dialog, cancellation, persistence, custom comments, deletion, narrow layout and save errors');
}
